command_timeout = 2000

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_purple)\
$directory\
[](fg:color_purple bg:color_blue)\
$git_branch\
$git_status\
[](fg:color_blue bg:color_aqua)\
$git_metrics\
[](fg:color_aqua bg:color_bg3)\
$time\
[ ](fg:color_bg3)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[directory]
style = "fg:color_fg0 bg:color_purple"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[git_branch]
style = "bg:color_blue"
format = '[[ $symbol$branch ](fg:color_fg0 bg:color_blue)]($style)'

[git_status]
style = "bg:color_blue"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_blue)]($style)'

[git_metrics]
disabled = false
added_style = "fg:color_fg0 bg:color_aqua"
deleted_style = "fg:color_fg0 bg:color_aqua"
format = '[[ +$added/-$deleted ](fg:color_fg0 bg:color_aqua)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg3"
format = '[[  $time ](fg:color_fg0 bg:color_bg3)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
