command_timeout = 2000

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](red)\
$directory\
[](fg:red bg:yellow)\
$git_branch\
$git_status\
[](fg:yellow bg:green)\
$git_metrics\
[](fg:green bg:blue)\
$time\
[ ](fg:blue)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
style = "bold fg:base bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[git_branch]
style = "bg:yellow"
format = '[[ $symbol$branch ](bold fg:base bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](bold fg:base bg:yellow)]($style)'

[git_metrics]
disabled = false
added_style = "bold fg:base bg:green"
deleted_style = "bold fg:base bg:green"
format = '[[ +$added/-$deleted ](bold fg:base bg:green)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:blue"
format = '[[  $time ](bold fg:base bg:blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
