[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[cursor]
style = { shape = "Beam", blinking = "Never" }

[mouse]
hide_when_typing = true

[window]
option_as_alt = "Both"

[general]
import = [
  "~/.dotfiles/.config/alacritty/themes/gruvbox_dark.toml"
]

[terminal]

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["-c", "zellij options --theme gruvbox-dark"]
